### ISSUE TITLE
Change the default branch for this repo to "dev"

### ISSUE THREAD

**Issue by mreid-moz** [mozilla-services/mozilla-pipeline-schemas#119]
This is easily done in settings, and should help avoid people sending PRs against master by force of habit.

**Comment by mreid-moz** [comment]
@trink @whd feedback? I'll go ahead and make the change if there are no objections.

**Comment by whd** [comment]
👍

**Comment by mreid-moz** [comment]
Done!

**Comment by trink** [comment]
heh -1

The dev branch will most likely go away with the continuous deployment work and switching it back to master later will create some minor confusion for existing checkouts of the repo.

**Comment by whd** [comment]
While this change might be short-lived, I think it's worth keeping the default as dev until we remove the dev branch to avoid a few extra clicks on every PR submission. When we do remove the branch the coinciding README.md changes should alleviate any confusion.
