### ISSUE TITLE
Add "accessibilityServices" property to the core schema.

### ISSUE THREAD

**Issue by yzen** [mozilla-services/mozilla-pipeline-schemas#141]
accessibilityServices are being added to tack enabled accessibility services that can interact with our android products and we would like to know how to best support them.

**Comment by mreid-moz** [comment]
Can you link to the bug/issue where this information is being added?

**Comment by yzen** [comment]
Here's the bug, it landed yesterday: https://bugzilla.mozilla.org/show_bug.cgi?id=1449212

**Comment by mreid-moz** [comment]
Resolved by #142
