### ISSUE TITLE
Can we see how many of the pings sent from the study add-on are passing the schema validation?

### ISSUE THREAD

**Issue by motin** [mozilla-services/mozilla-pipeline-schemas#152]
We are seeing considerably fewer pings ending up in [our study](https://github.com/motin/esper-pioneer-shield-study)'s parquet table than expected compared to the Normandy recipe's DAU estimates and are exploring possible sources to this discrepancy. 

What happens if a payload does not pass the schema validation? Does such events leave some traces in a log somewhere? (We have yet not implemented schema validation in the add-on but may add that in a future version)

**Comment by mreid-moz** [comment]
There is a table you can query in STMO - you can do something like:
`SELECT fields.doc_type, fields.decode_error FROM telemetry_errors_parquet WHERE submission_date_s3 = '20180718' LIMIT 5`

You can filter for `fields.doc_type = 'pioneer-study'` to limit to the subset of pings that are of interest.
