### ISSUE TITLE
Fix new profile json / parquet schema mismatch

### ISSUE THREAD

**Issue by whd** [mozilla-services/mozilla-pipeline-schemas#166]
/CC @mreid-moz 

https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/new-profile/new-profile.4.parquetmr.txt#L66-L69
https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/new-profile/new-profile.4.schema.json#L373-L383

My understanding is that in the parquet schema, we're saying that profile is optional, but if it exists it must contain `creationDate`, whereas in the json schema we do not make this second stipulation. This is causing our parquet output to drop pings that have a profile of `{}`.

My guess would be that we want to relax the parquet schema, but since we may want to make the JSON schema stricter instead I've created an issue instead of a PR. From our new monitoring this represents 1-2% of pings, which may be significant enough as to require a backfill (in which case we should also file a separate bug for that).

**Comment by mreid-moz** [comment]
The new-profile ping shares the same `environment` blob as all the other Telemetry pings, so I think we should just relax the parquet schema to match.

**Comment by mreid-moz** [comment]
Fixed by #168
