### ISSUE TITLE
Checking against underscores in the ping title

### ISSUE THREAD

**Issue by florian** [mozilla-services/mozilla-pipeline-schemas#172]
It seems like it is not possible to use underscores in the title of a ping. If I use `TelemetryController.submitExternalPing` on the client and provide a ping title with an underscore, I get the following error:
> Error: Invalid type string submitted.

It would probably a good idea for the schema validator to check for this automatically.

**Comment by acmiyaguchi** [comment]
The schema name is is being enforced in the latest version of the CMakeLists for this:

https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/698fdb13e58338def105ac8ac34145571f65e676/CMakeLists.txt#L62
