### ISSUE TITLE
Making sure Shield schemas are available for Pioneer telemetry

### ISSUE THREAD

**Issue by motin** [mozilla-services/mozilla-pipeline-schemas#199]
With https://github.com/mozilla/shield-studies-addon-utils/pull/263, we will be submitting Pioneer telemetry in the same format as ordinary Shield studies. I'd like to know if there is anything we need to do for Pioneer telemetry to be properly processed, given that the shield schemas already are available in this repo, albeit in the `telemetry` namespace instead of the `pioneer-study` namespace?

(The client [supplies the schema name (shield-study, shield-study-addon or shield-study-error) and version (3)](https://github.com/mozilla/shield-studies-addon-utils/pull/263/files#diff-fdcc1f0e5fcb202a267bed8390220152R297) when sending off Pioneer telemetry)

**Comment by mlopatka** [comment]
@mreid-moz @trink 
Can we get this issue triaged? 

We have a study planned for November 5th and need confirmation that our pioneer utils pings are going to get delivered. 

cheers!

**Comment by mreid-moz** [comment]
@motin I *think* you will need to include those schemas inside the `pioneer-study` namespace (you can use the templating functionality for this to avoid copying). 

Can you provide an example document as it will be submitted?

**Comment by trink** [comment]
@mreid-moz is correct the nested schema lookup will happen in pioneer-study, also +1 for adding the duplicated schemas as templates and having both locations reference the single instance.

**Comment by motin** [comment]
Thanks for the feedback. How would you prefer that we proceed? According to https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/README.shield.md the shield study schemas in this repo are generated. The proper way would be to also generate the schemas in the pioneer-study namespace, but I am not sure where the code for that build step resides. 

Also, some example documents are provided in the external repo and seem not be included at all in this repo.

I created the above PR with duplication of the files and creation of example documents based on https://github.com/gregglind/shield-study-schemas/blob/master/example.valid.packets.json while we figure out the proper way to fix this.

**Comment by motin** [comment]
Ping @gregglind

**Comment by motin** [comment]
(Discussion moved to https://github.com/mozilla/openwpm-webext-instrumentation/pull/7)

**Comment by motin** [comment]
Glad to see that the PR was merged :)
We can close this issue ss soon as we see packets arriving safely.

**Comment by whd** [comment]
These packets are not being decoded correctly. Here is an example error:

    :Uuid: b2004740-cc74-4b75-a934-d842310e0656
    :Timestamp: 2018-10-29T17:33:17.430968832Z
    :Fields:
        | name: uri type: 0 representation: <nil> value: /submit/telemetry/91a3508d-cd05-c844-86c0-763be582a2a0/pioneer-study/Firefox/63.0/aurora/20181008155858
        | name: args type: 0 representation: <nil> value: v=4
        | name: protocol type: 0 representation: <nil> value: HTTP/1.1
        | name: Content-Length type: 0 representation: <nil> value: 3989
        | name: Date type: 0 representation: <nil> value: Mon, 29 Oct 2018 17:33:17 GMT
        | name: Host type: 0 representation: <nil> value: incoming.telemetry.mozilla.org
        | name: User-Agent type: 0 representation: <nil> value: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:63.0) Gecko/20100101 Firefox/63.0
        | name: content type: 1 representation: <nil> value: <lots of bytes>
        | name: DecodeErrorType type: 0 representation: <nil> value: schema
        | name: DecodeError type: 0 representation: <nil> value: no schema: shield-study-addon.3 study: jestr-pioneer-shield-study@pioneer.mozilla.org
        | name: DecodeErrorDetail type: 0 representation: <nil> value:
        | name: schemaName type: 0 representation: <nil> value: shield-study-addon
        | name: geoSubdivision1 type: 0 representation: <nil> value: 18
        | name: studyName type: 0 representation: <nil> value: jestr-pioneer-shield-study@pioneer.mozilla.org
        | name: schemaVersion type: 3 representation: <nil> value: 3
        | name: pioneerId type: 0 representation: <nil> value: cf7ff02b-0c3f-8949-a9c6-816e63005fb4
        | name: normalizedChannel type: 0 representation: <nil> value: aurora
        | name: appUpdateChannel type: 0 representation: <nil> value: aurora
        | name: appVendor type: 0 representation: <nil> value: Mozilla
        | name: documentId type: 0 representation: <nil> value: 91a3508d-cd05-c844-86c0-763be582a2a0
        | name: docType type: 0 representation: <nil> value: pioneer-study
        | name: appBuildId type: 0 representation: <nil> value: 20181008155858
        | name: geoCountry type: 0 representation: <nil> value: FI
        | name: creationTimestamp type: 3 representation: <nil> value: 1.5408343973e+18
        | name: geoCity type: 0 representation: <nil> value: Helsinki
        | name: appVersion type: 0 representation: <nil> value: 63.0
        | name: appName type: 0 representation: <nil> value: Firefox

**Comment by whd** [comment]
Actually, the timestamp from above is probably before this was merged and deployed, but I don't see any non-errors in the stream. @motin if you could send some more data so that we can confirm the pipeline is working that would be great.

**Comment by motin** [comment]
I just sent about 100-200 packages down the pipe - about 60 seconds ago now :)

**Comment by whd** [comment]
Ok, I'm seeing decoded data that is being routed to the new pioneer-shield-study-addon-parquet dataset (and no errors), so I think we're good here.

**Comment by motin** [comment]
Great news @whd!
@mlopatka Please comment in this thread if the packets can also be decrypted and parsed.

**Comment by mlopatka** [comment]
Ok, I did some superficial filtering on the new pings arriving on Bastion.

At this moment I can only detect pings from one single PioneerID.

even under very lenient filtering conditions:
filtering only on study name as: 'jestr-pioneer-shield-study@pioneer.mozilla.org'
`len([set(pings.map(lambda p: p['meta']['pioneerId']).collect())])
> 1
`
I have spoken with three confirmed testers of this addon. 

Will investigate further on Monday.

**Comment by mlopatka** [comment]
So I am able to see the raw pings via the following query:
```
pings = Dataset.from_source("pioneer-study") \
    .where(studyName='jestr_pioneer_shield_study_pioneer.mozilla.org').records(sc)
```
The `pioneer-study` table was not listed among the direct to parquet 
( Huge thanks to @sunahsuh for tracking down the payloads. )

I've now verified the pings sent during testing are all accounted for. This issue can be closed.

**Comment by mreid-moz** [comment]
Thanks @mlopatka !
