### ISSUE TITLE
Add AArch64 platform to installer schema (Bugzilla bug 1514799)

### ISSUE THREAD

**Issue by mhowell-mozilla** [mozilla-services/mozilla-pipeline-schemas#237]
Currently the installer ping has boolean fields for 64bit_build and 64bit_os, which are false for x86 and true for x64. We're now adding support for AArch64, so booleans are no longer enough and those need to be replaced by enums that allow x86, x64, and AArch64.

**Comment by acmiyaguchi** [comment]
Closed to reflect the status in #247
