### ISSUE TITLE
Modules ping schema validation errors

### ISSUE THREAD

**Issue by whd** [mozilla-services/mozilla-pipeline-schemas#240]
We're seeing a slightly higher than 1% error rate on modules pings (which I believe are pre-release only): https://pipeline-cep.prod.mozaws.net/dashboard_output/graphs/analysis.moz_telemetry_doctype_monitor_modules.ingestion_error.html

Here's such an error:
    schema: modules version: 4 validation error: SchemaURI: #/properties/environment/properties/addons/properties/activeAddons/additionalProperties/properties/scope Keyword: type DocumentURI: #/environment/addons/activeAddons/ADDON/scope

Here's a more detailed error message, which indicates it might be a type or missing property issue: 

    name: DecodeErrorDetail type: 0 representation: <nil> value: {"type":{"expected":["integer"],"actual":"null","instanceRef":"#/environment/addons/activeAddons/ADDON/scope","schemaRef":"#/properties/environment/properties/addons/properties/activeAddons/additionalProperties/properties/scope"}}

**Comment by whd** [comment]
@marco-c it appears from git blame you might know who could take a look at this. 
Here's an example entry from environment.activeAddons that has a null scope:


        "formautofill@mozilla.org": {
            "appDisabled": false,
            "blocklisted": false,
            "description": null,
            "foreignInstall": false,
            "hasBinaryComponents": false,
            "installDay": 17722,
            "isSystem": true,
            "isWebExtension": true,
            "multiprocessCompatible": true,
            "name": "Form Autofill",
            "scope": 1,
            "type": "extension",
            "updateDay": 17886,
            "userDisabled": false,
            "version": "1.0"
        },

We should update the schemas to allow a null scope, fix the client so it doesn't send the null scope, or (possibly, if this is very unimportant) ignore these errors.

**Comment by whd** [comment]
That's true, this seemingly should affect other pings, but since modules is such low volume the percentage of pings for which it affects is relatively large. @mreid-moz can you take a look at this and figure out who should investigate?

https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/templates/include/telemetry/environment.1.schema.json#L30

**Comment by mreid-moz** [comment]
This should be fixed by #244
