### ISSUE TITLE
Document use of branches in this repo

### ISSUE THREAD

**Issue by mreid-moz** [mozilla-services/mozilla-pipeline-schemas#261]
I keep forgetting why we use `dev` rather than `master` here.

Also, should we merge `dev` -> `master` on each deploy? Then it'd be easy to see what has or hasn't been deployed.

cc @trink @whd

**Comment by trink** [comment]
It allowed us to pre test everything that has changed before merging to master and creating the production package. Since we don't do that anymore, you can move everything to master and delete dev

**Comment by mreid-moz** [comment]
Closing this issue - instead let's switch back to using `master` as expected.
