### ISSUE TITLE
Sherlock Holmes and the case of the missing schemas

### ISSUE THREAD

**Issue by whd** [mozilla-services/mozilla-pipeline-schemas#262]
@mreid-moz for the title

Here's a list of every known ping type, more or less. For GCP we require schemas to decode submissions. I'm guessing at least some of these pings (e.g. loop) we no longer care about and can therefore ignore, but there are definitely some (e.g. sync) that we need to create a schema for. The current plan is to create a GCP testing branch to add these new schemas to, and backport those schemas into AWS if/when necessary. I don't have volume estimates for a lot of these (essentially those that we also don't have schemas for, sadly) but with @trink's upcoming auto-bootstrapped doctype monitoring we might be able to get that information automatically.

There's also nothing as to `docVersion` in the list I generated, which may end up being relevant for pings with multiple `docVersions`.

In terms of prioritization, I've made a first pass by **emboldening** pings that I think are probably important and _italicizing_ pings that we probably don't care about anymore.

  - [ ] **activation**
  - [ ] addon-install-blocked
  - [ ] advancedtelemetry
  - [ ] android-anr-report
  - [X] anonymous
  - [ ] appusage
  - [ ] _b2g-installer-device_
  - [ ] _b2g-installer-flash_
  - [ ] **bhr**
  - [X] block-autoplay
  - [ ] certificate-checker
  - [X] core
  - [X] crash
  - [ ] **deletion**
  - [ ] deployment-checker
  - [ ] _disableSHA1rollout_
  - [X] downgrade
  - [X] event
  - [ ] **first-shutdown**
  - [ ] _flash-shield-study_
  - [ ] flash-video
  - [X] focus-event
  - [X] frecency-update
  - [ ] ftu
  - [X] health
  - [X] heartbeat
  - [ ] idle-daily
  - [ ] _loop_
  - [X] main
  - [ ] malware-addon-states
  - [X] mobile-event
  - [X] mobile-metrics
  - [X] modules
  - [X] new-profile
  - [X] optout
  - [ ] outofdate-notifications-system-addon
  - [X] pioneer-study
  - [X] saved-session
  - [ ] **searchvol**
  - [ ] **searchvolextra**
  - [X] shield-icq-v1
  - [X] shield-study
  - [X] shield-study-addon (sort of)
  - [X] shield-study-error
  - [ ] _shield-study-icq_
  - [ ] **sync**
  - [ ] system-addon-deployment-diagnostics
  - [X] testpilot
  - [ ] _testpilottest_
  - [ ] _tls13-middlebox-alt-server-hello-1_
  - [ ] _tls13-middlebox-beta_
  - [ ] _tls13-middlebox-draft22_
  - [ ] _tls13-middlebox-ghack_
  - [ ] _tls13-middlebox-repetition_
  - [ ] _tls13-middlebox-testing_
  - [ ] _tls-13-study_
  - [ ] _tls-13-study-v1_
  - [ ] _tls-13-study-v2_
  - [ ] _tls-13-study-v3_
  - [ ] _tls-13-study-v4_
  - [ ] uitour-tag
  - [X] untrustedModules
  - [X] update
  - [ ] x-contextual-feature-recommendation

**Comment by mreid-moz** [comment]
See https://github.com/mozilla/gcp-ingestion/issues/450 for a possible way to make this problem less problematic.

**Comment by whd** [comment]
Closing this via #450, we can add additional placeholders as needed using the same placeholder schema.
