### ISSUE TITLE
Drop old `Glean` data and deploy breaking changes

### ISSUE THREAD

**Issue by fbertsch** [mozilla-services/mozilla-pipeline-schemas#272]
This may happen again in the future, but we've decided that until we have a stable Glean release, the data can be considered transient.

Parts of this change should be:
1. Remove UUID from the metadata section
2. Change `clientId` to `client_id`
3. Add `first_added_date` to `ping_info` section
4. Move v2 to v1, and drop v1 (this will need a parallel client change)

Any other breaking change that we know are immediately incoming should be added here. Once they are merged we can delete the old data and deploy the new schemas.

**Comment by fbertsch** [comment]
Dependent PRs:
- https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/271
- https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/270
- https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/269
- https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/260

Still need a PR for moving v1 -> v2.

**Comment by mdboom** [comment]
The glean library in android-components has been moved to point to this as of https://github.com/mozilla-mobile/android-components/pull/2181.

I think all that's left is deployment.  @fbertsch : How does that work?

**Comment by whd** [comment]
I've deployed this and dropped all the data up until today. I think we're good here but I'll leave it to @fbertsch to confirm.

**Comment by fbertsch** [comment]
This is done.
