### ISSUE TITLE
Add auto-generated Avro and BigQuery schemas

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla-services/mozilla-pipeline-schemas#306]
I'm interested in adding auto-generates schemas for Avro and BigQuery in this repository. I created a tool for converting JSON Schema into these formats so that we can ingest pings directly into BigQuery tables. The latest stable version can be found [here](https://github.com/acmiyaguchi/jsonschema-transpiler/tree/0.2). 

I've tested that the schemas can be used with the avro library to generate binary payloads. I've created a sample BigQuery project using sampled documents from the AWS landfill and the generated schemas [here](https://console.cloud.google.com/bigquery?project=test-avro-ingest&p=test-avro-ingest&page=project) (ping me for access). 

I have a branch with the schemas [here](https://github.com/acmiyaguchi/mozilla-pipeline-schemas/tree/transpiled-schemas). There are a few caveats to the tool that should be mentioned:

* all numbers and integers are 64 bits
* field names are converted to match BigQuery column naming rules
* under-specified or unsupported schema fields are casted into strings

**Comment by acmiyaguchi** [comment]
@trink Do you think it's reasonable to keep auto-generated schemas in this repo?

There are a couple of things that I'd like to do within the potential PR. First is adding the `jsonschema-transpiler` binary to the cmakelists like `parquetfmt`. Is there an easy way to generate binaries for cross platform usage? Secondly, I have a python script that uses `avro-python3` to create a canonical form of the avro schemas because it would have taken some time to implement it from scratch in rust. Can I run python3 scripts within cmake?

**Comment by trink** [comment]
I am not a fan of keeping auto-generated schema in the repo... but it is being done now.  It currently adds a slight burden to the developer as they are responsible for committing them and requires them to have the tooling installed to do the work.

- The best way to auto generate binaries for each platform is CI
- CMake can call out to anything but the build environment would have to contain the underlying tooling (you could add some CMake checks and fail the build for the benefit of developers that build locally pointing them at the setup instructions).

**Comment by jklukas** [comment]
> I am not a fan of keeping auto-generated schema in the repo... but it is being done now. It currently adds a slight burden to the developer as they are responsible for committing them and requires them to have the tooling installed to do the work.

I would agree that in general requiring the developer to run generation code and check in the results is a pain, but in the context of a repo like this where that generated content is the central focus, I find the benefits are entirely worth it and I feel we are far enough over that threshold that we should feel free to fully embrace the possibilities of generating content.

As for installing tooling, I vote that we move to having developers invoke a script that builds and executes docker containers with mounts such that they can write output to the local filesystem. That would reduce the number of dependencies that developers have to install to one, and it would allow us to have a different dependency chain for the various types of schemas we need to generate.

**Comment by jklukas** [comment]
> The best way to auto generate binaries for each platform is CI

A benefit I really enjoy from having generated schemas checked into this repository is the discoverability and browsability in the GitHub UI. It's currently possible to send somebody a link to the full generated JSON schema for any docType. I see a lot of benefit of having the same discoverability for avro and bq schemas.

We don't get that same visibility into the generated schemas if they're produced in CI and stored as an artifact.

**Comment by trink** [comment]
I agree having the generated schemas visible and reviewable is nice but that doesn't necessarily mean they need to be in the repo, it was just the easiest solution at the time.  If we continue down that path the +1 to docker containers.

**Comment by jklukas** [comment]
I'm going to advertise this issue in some IRC and Slack channels to see if we can get some feedback from those who have interacted more peripherally with this repo.

**Comment by mdboom** [comment]
> It's currently possible to send somebody a link to the full generated JSON schema for any docType.

This isn't **exactly** what's being discussed here, since it doesn't relate to these *new* products, but I wanted to point out that the glean unit tests currently checks the output glean generates by downloading the full expanded JSON schema from a raw github url and validating against that.  So that's a use case of an external tool finding it convenient to have a ready-to-use schema just available at a public URL.  Like has already been said, that doesn't have to be a git repo, but publicly accessible somewhere with an easy URL I feel is a hard requirement.

**Comment by jklukas** [comment]
Quick update here that @fbertsch is drafting a wider proposal for generation of BQ and avro schemas that will be available for review early next week. BQ schemas are going to depend on some additional input that doesn't live directly in this repo, so a CI-based approach is seeming necessary. But the proposal will likely include pushing the produced schemas to a branch of this repo as one of the outputs, so we get the discoverability benefits discussed in this issue.

**Comment by acmiyaguchi** [comment]
Thanks for the good discussion here. It looks like the main goal is an easy local development workflow with a public URL that can be referenced once deployed.

I think a reasonable step forward is to maintain the current review and development workflow, while swapping over to docker as the primary build and test tooling. This means every modification to the repo will include diffs to the BigQuery and Avro schemas. It should be easier to spot schema-incompatible changes in the resulting diffs. We'll be able to reference all the generated schemas in any revision as long as Github is up.

> BQ schemas are going to depend on some additional input that doesn't live directly in this repo, so a CI-based approach is seeming necessary.

To expand on this, we want to build full schemas where `additionalProperties` are replaced with `properties`. The schema transpiler will create a structure instead of a key-value map. This representation should help avoid `UNNEST` or `explode` in SQL. CI will need to trigger builds on two classes of events - merges into master and updates to the probe-info-service.

![image](https://user-images.githubusercontent.com/3304040/56066709-7affb280-5d2d-11e9-9f2b-0fbc9d10cbef.png)

It comes back to the question of checking the schemas back into the repository or generating artifacts that can be referenced. 

--- 

As a tangent, I would like to include support for Parquet schemas in the future (https://github.com/acmiyaguchi/jsonschema-transpiler/issues/41). It might be worth checking in schemas into the repository as a dependency of the validation checks where the validation documents are serialized from JSON into Parquet. This is also valid for the JSON -> Avro -> BigQuery pipeline.

**Comment by acmiyaguchi** [comment]
We've been committing bigquery schemas into a generated-schemas branch for some time now. The process is documented in https://docs.telemetry.mozilla.org/concepts/pipeline/schemas.html
