### ISSUE TITLE
output.telemetry_telemetry_pre_account_4_parquet_s3 process_message returned: -1 column 'speedMHz' is required

### ISSUE THREAD

**Issue by whd** [mozilla-services/mozilla-pipeline-schemas#313]
/CC @badboy 

The pre-account ping schemas were deployed recently and I'm seeing occasional errors of the type above.  It looks like this is because the json schema has the field as required but nullable, but the parquet schema has it as required. I'm a little hazy as to null vs optional, @trink would know more, but making the field optional in parquet is probably sufficient to fix the issue. You should be able to reproduce this in the tests by making the [field](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/validation/telemetry/pre-account.4.sample.pass.json#L56) null.

https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/pre-account/pre-account.4.schema.json#L89-L93
https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/pre-account/pre-account.4.parquetmr.txt#L35-L37

**Comment by badboy** [comment]
Thanks, there are even other nullable fields that are marked as required in parquet. Fixing those as well, PR inbound.
