### ISSUE TITLE
Please setup a pipeline for Firefox Preview Beta

### ISSUE THREAD

**Issue by sarentz** [mozilla-services/mozilla-pipeline-schemas#322]
I am not sure what information to put in here, but our goal is to ship 'Firefox Preview Beta' on May 1st. This is a new app with a new app identifier: `org.mozilla.fenix.beta`.

Please let me know what other information I should provide.

**Comment by mitchhentges** [comment]
Heads up that we have a bugzilla for this [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1545401)

**Comment by jklukas** [comment]
cc @fbertsch 

I believe that all we need to do for this is to add an entry in mozilla-schema-generator config similar to this stanza for Fenix nightly: https://github.com/mozilla/probe-scraper/blob/master/repositories.yaml#L40-L52

**Comment by jklukas** [comment]
Now that I think about this more, it may be the existing `org-mozilla-fenix` namespace corresponds to the beta that is referenced here, so no further changes needed.

**Comment by fbertsch** [comment]
It is that one, nothing to do here.
