### ISSUE TITLE
Ignore generated-schemas branch in CI

### ISSUE THREAD

**Issue by whd** [mozilla-services/mozilla-pipeline-schemas#337]
or do something appropriate, currently since there is no circle CI config for that branch it fails ala https://circleci.com/gh/mozilla-services/mozilla-pipeline-schemas/1267.

**Comment by jklukas** [comment]
The appropriate thing is probably to make sure that the script that pushes changes there always includes "[skip ci]" in the commit message](https://circleci.com/docs/2.0/skip-build/?gclid=EAIaIQobChMI_bbb9f654wIVAdvACh2YzwoqEAAYASAAEgJ5V_D_BwE#skipping-a-build).

**Comment by whd** [comment]
Resolved by https://github.com/mozilla/mozilla-schema-generator/pull/46
