### ISSUE TITLE
schema: modules version: 4 validation error: SchemaURI: #/properties/environment/properties/addons/properties/theme/properties/updateDay Keyword: type DocumentURI: #/environment/addons/theme/updateDay

### ISSUE THREAD

**Issue by whd** [mozilla-services/mozilla-pipeline-schemas#341]
[11:30:20] <whd> 3% of modules nightly pings
    [11:30:39] <whd> but the error itself is with the environment, so maybe it matters that we investigate it
    [11:31:05] <whd> I didn't see any change related to updateDay or whatever it is in any recent schemas updates so I'm not sure what the deal is
    [11:31:41] <whd> actually over the weekend it went from 1% (alert threshold) to 5% today

**Comment by whd** [comment]
Looks like [we're seeing nulls](https://pipeline-cep.prod.mozaws.net/dashboard_output/analysis.dl.dt_telemetry_modules.captures.json):

    {
        "errors": [
            {
                "type": {
                    "actual": "null",
                    "expected": [
                        "integer"
                    ],
                    "instanceRef": "#/environment/addons/theme/updateDay",
                    "schemaRef": "#/properties/environment/properties/addons/properties/theme/properties/updateDay"
                }
            }
        ]
    }

**Comment by whd** [comment]
This is up to 6% of nightly and just recently fired for 1% of beta. It's somewhat strange that it's only firing for modules pings.

**Comment by mreid-moz** [comment]
Looks like we're seeing null in this field.

**Comment by whd** [comment]
Thanks for handling this @mreid-moz, the fix appears to have worked.
