### ISSUE TITLE
schema: downgrade version: 4 validation error: SchemaURI: #/properties/payload/properties/lastVersion Keyword: pattern DocumentURI: #/payload/lastVersion

### ISSUE THREAD

**Issue by whd** [mozilla-services/mozilla-pipeline-schemas#347]

**Comment by acmiyaguchi** [comment]
This was recently rediscovered during a weekly health check: https://bugzilla.mozilla.org/show_bug.cgi?id=1612938

**Comment by acmiyaguchi** [comment]
Reflecting the status of the bug, in which this resolved naturally.
