### ISSUE TITLE
Fail CI for camelCase docTypes or namespaces

### ISSUE THREAD

**Issue by jklukas** [mozilla-services/mozilla-pipeline-schemas#355]
Similar to https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/318, we should fail CI if a namespace or schema is introduced that uses camelCase naming. This makes it more difficult to have standard tooling around these schemas.

Likely the easiest thing to check if that the directory and file names contain no capital letters. We'll need to have an exemption for the existing non-compliant docType `untrustedModules`.

**Comment by acmiyaguchi** [comment]
Fixed in https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/616
