### ISSUE TITLE
Expired certificate prevents Docker tests

### ISSUE THREAD

**Issue by jklukas** [mozilla-services/mozilla-pipeline-schemas#358]
I just purged the docker cache on my local machine and tried to run the docker-based tests in this repo. I received the following error when building the image:

```
--2019-07-22 16:19:15--  https://hsadmin.trink.com/packages/centos7/sprintAug21.tgz
Resolving hsadmin.trink.com (hsadmin.trink.com)... 54.213.28.47
Connecting to hsadmin.trink.com (hsadmin.trink.com)|54.213.28.47|:443... connected.
ERROR: cannot verify hsadmin.trink.com's certificate, issued by '/C=US/O=Let\'s Encrypt/CN=Let\'s Encrypt Authority X3':
  Issued certificate has expired.
To connect to hsadmin.trink.com insecurely, use `--no-check-certificate'.
--2019-07-22 16:19:15--  https://hsadmin.trink.com/packages/centos7/external/parquet-cpp-0.0.1-Linux.rpm
Connecting to hsadmin.trink.com (hsadmin.trink.com)|54.213.28.47|:443... connected.
ERROR: cannot verify hsadmin.trink.com's certificate, issued by '/C=US/O=Let\'s Encrypt/CN=Let\'s Encrypt Authority X3':
  Issued certificate has expired.
To connect to hsadmin.trink.com insecurely, use `--no-check-certificate'.
```

Enivornments where this layer is already cached may be continuing to work fine.

When I try to hit the site in Firefox, it tells me the certificate expired on 7/10/2019, so about two weeks ago.

cc @trink.

**Comment by trink** [comment]
The box is being deprecated this month, nothing *should* be reading from it.  All tests should be pointing to the official packages in S3.

**Comment by trink** [comment]
The reference was removed here
https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/9cd82aa21e9b05717ce53ab3bcd8b60b3d5d62d5#diff-3254677a7917c6c01f55212f86c57fbf
