### ISSUE TITLE
Create non-camelCased untrusted-modules.5.schema.json

### ISSUE THREAD

**Issue by jklukas** [mozilla-services/mozilla-pipeline-schemas#367]
We have only one schema in this repository that uses a camelCase name, and it causes some pain for conversions to BigQuery. I'd propose bumping the version and copying the schema into `untrusted-modules.5.schema.json`. We can transition new versions of Firefox to use that name so that we can eventually retire the old version and simplify tooling.

cc @mreid-moz @relud for thoughts or objections

**Comment by whd** [comment]
Shortly after this was filed we discovered that there's actually another case with [disableSHA1rollout](https://github.com/mozilla/mozilla-schema-generator/issues/48). This docType is from a long time ago and was rolled out via system addon, so we probably don't care about it anymore, and I would not expect to be able to update clients to stop sending it to us. Perhaps eventually we could simply drop the current schemas for disableSHA1rollout and stop processing this data.

**Comment by acmiyaguchi** [comment]
Fixed in https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/616
