### ISSUE TITLE
Transpile "pipeline family" schemas

### ISSUE THREAD

**Issue by relud** [mozilla-services/mozilla-pipeline-schemas#373]
as per @whd's [PR comment] https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/372#issuecomment-518410996

> One thing to note here is that if we're planning on using the standard transpiler to convert these into BQ schemas (and then wind up in the generated-schemas branch), we're going to also need to update MSG to that effect. Currently we simply remove them.
> 
> The BQ table management (WIP here) for these tables will have special case logic since they are generated by "pipeline family", which isn't a concept propagated to this repository.

**Comment by whd** [comment]
Moving to https://github.com/mozilla/mozilla-schema-generator/issues/52
