### ISSUE TITLE
Proposal: Restrict Glean DocType naming to be kebab-case

### ISSUE THREAD

**Issue by jklukas** [mozilla-services/mozilla-pipeline-schemas#390]
As discussed in https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/387#issuecomment-522151389, we have near complete consistency of kebab-case docType naming in this repository. Besides a few camelCase docTypes, we have two snake_case docTypes from fenix.

@fbertsch mentioned that @mdboom would be the person to talk to about potentially adding restrictions on future glean docTypes to match kebab-casing. I don't have a solid understanding of all the layers involved with a glean user choosing to implement a new docType, so it's not clear to me what options we have.

**Comment by jklukas** [comment]
@mdboom is on PTO right now but briefly responded that this should be possible to enforce.

**Comment by mdboom** [comment]
I'm back for the day :)

I'm happy to self-assign for the implementation (which should be straightforward), but first some things for discussion --

Basically I think the way to enforce this would be to add regexes for ping names in the glean_parser schemas [here](https://github.com/mozilla/glean_parser/tree/master/glean_parser/schemas).  It looks as if in #387 we already enforce these things in this repo.

We concerns would just be around data migration.  If we rename the two in fenix from snake to kebab case, does that affect existing collected data?  These doctypes actually come the the sync library (not Fenix directly), so we would need to update there and then wait for Fenix to uplift to a new version of android-components.  Any possible gotchas there?

**Comment by jklukas** [comment]
>  If we rename the two in fenix from snake to kebab case, does that affect existing collected data?

We have support in the GCP pipeline at this point to normalize schema names before looking up schemas for validation. So pings will be treated the same whether the docType in the url is `bookmarks-sync` or `bookmarks_sync`. Fenix should be able to upgrade at whatever point, and the pipeline will be able to handle either variant.

The thing I don't fully understand is what the sequencing looks like for schema generation. I'm inclined to update mps to add a symlink for `bookmarks-sync` alongside `bookmarks_sync`, etc. and then make sure that the schema generator ignores the snake_case variants when generating bq schemas. There may need to be an update for the schema generator, though, to support both variants, since I'm assuming it'll see the snake_case version in the probe info service and only inject probes into that schema and not the kebab-case version until the master branch of fenix pulls in a sync lib version that includes the kebab-case change. cc @fbertsch

**Comment by jklukas** [comment]
>  It looks as if in #387 we already enforce these things in this repo.

#387 was a proposal to standardize on snake_case in this repo, but we closed that without merging. The PR generated some great discussion and we agreed to stick with and start enforcing the documented kebab-case style for MPS. We then rely on the schema generation pipeline to enforce snake case for BigQuery table schemas.

I'm looking at the schema definition for pings.yaml and am trying to think through the implications of:

```
  The top-level of the `pings.yaml` file has a key defining the name of each
  ping. The values contain metadata about that ping. Ping names must be
  snake_case, though they may also have dots `.` to define subcategories.
```

This seems contradictory to [the DTMO docs on choosing a doctype name](https://docs.telemetry.mozilla.org/cookbooks/new_ping.html#choose-a-namespace-and-doctype):

> Both namespace and DocType are limited to the pattern [a-zA-Z-]

If snake_case makes sense within the overall style of the yaml files used for defining glean metrics, I'm potentially fine with having names be specified in snake_case in the yaml. But in that case, I'd like the glean machinery to convert those names to kebab case when constructing the uri for sending a ping.

**Comment by jklukas** [comment]
I can understand that Glean metric names might contain `.` for defining subcategories, but the same doesn't make sense for ping names. Should the regex for ping names really allow a `.`? A period in a docType could potentially break or be rejected by the GCP ingestion pipeline.

**Comment by mdboom** [comment]
Yeah -- I don't remember the provenance of using dots for categories in ping names.  @Dexterp37 ?

**Comment by Dexterp37** [comment]
> 
> 
> Yeah -- I don't remember the provenance of using dots for categories in ping names. @Dexterp37 ?

I don't think we have a strong argument for supporting dots in ping names. We don't have any [documented ping name](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/index.html) that contains a dot and I think it would be ok to restrict ping names *to not have dots in them*. The only reason I could think they might be useful for would be to allow for versioning in the ping name, which sounds... eugh :)

@chutten , given that this will affect Desktop too (once we make it Gleany), do you have opinions on this?

**Comment by acmiyaguchi** [comment]
This is now (and has been for some time) the defacto standard. Thanks @jklukas for standardizing naming conventions throughout the repository.
