### ISSUE TITLE
Please add "e10sCohort" to the main ping schema

### ISSUE THREAD

**Issue by felipc** [mozilla-services/mozilla-pipeline-schemas#4]
This is a string field, stored in telemetryEnvironment.settings.e10sCohort.

Possible values:
- unsupportedChannel
- optedIn
- optedOut
- test
- control
- unknown

More details at https://bugzilla.mozilla.org/show_bug.cgi?id=1249845 and https://bugzilla.mozilla.org/show_bug.cgi?id=1251259

Happy to answer any questions

**Comment by georgf** [comment]
I added this to #1.

**Comment by mreid-moz** [comment]
Resolved by #1
