### ISSUE TITLE
Add checks to CI for potential gotchas

### ISSUE THREAD

**Issue by sunahsuh** [mozilla-services/mozilla-pipeline-schemas#413]
- Add special rule for pinned telemetry schema version (currently 4)
- Enforce directory structure for all schemas

**Comment by acmiyaguchi** [comment]
These conditions are being asserted.

Version numbers in testing:
https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/698fdb13e58338def105ac8ac34145571f65e676/tests/test_telemetry_version.py#L20-L26

Directory path depth
https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/698fdb13e58338def105ac8ac34145571f65e676/tests/conftest.py#L15-L21

Validation document depth
https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/698fdb13e58338def105ac8ac34145571f65e676/tests/conftest.py#L37-L43
