### ISSUE TITLE
rapidjson only supports JSON Schema Draft 4

### ISSUE THREAD

**Issue by mdboom** [mozilla-services/mozilla-pipeline-schemas#414]
The [rapidjson](https://github.com/Tencent/rapidjson) library being used for JSON schema validation here only supports draft 4.

Glean has already been using some Draft 6 features unknowingly for sometime, but this was only noticed when #408 added a test.  Specifically, the keyword is [propertyNames](https://json-schema.org/understanding-json-schema/reference/object.html?highlight=propertynames#property-names) which lets the schema restrict the keys on an object to a particular schema (in this case a regex pattern and a maxLength).

It doesn't look like rapidjson has ever been updated to Draft 6, so this isn't a straightforward upgrade, and of course updating the validator in production is likely to have far-reaching consequences and not to be taken lightly.

I'm mainly filing this issue to document the shortcoming and begin a discussion.

Should we (at minimum) add a note to the README?

**Comment by jklukas** [comment]
See https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/332 for thoughts on updating this repo to use the same validation library as the GCP pipeline, including Draft 7 support.

**Comment by mdboom** [comment]
Thanks, @jklukas.  #332 would indeed fix this.  Should we close as duplicate?

**Comment by jklukas** [comment]
Closing as duplicate.
