### ISSUE TITLE
The symlink in mozilla-pipeline-schemas/templates/telemetry/disable-sha1rollout fails the build on Windows (using WSL)

### ISSUE THREAD

**Issue by chutten** [mozilla-services/mozilla-pipeline-schemas#446]
This is what `cmake ..` gives me on today's master:

```bash
...
generating: schemas/telemetry/disable-sha1rollout/disable-sha1rollout.4.schema.json
parse error: Invalid numeric literal at line 2, column 0
CMake Error at CMakeLists.txt:78 (message):
  jq output error 4
  telemetry/disable-sha1rollout/disable-sha1rollout.4.schema.json


-- Configuring incomplete, errors occurred!
```

**Comment by jklukas** [comment]
I didn't realize symlinks in a git repo wouldn't work on Windows. We could probably add something to the build script to handle this, but it's probably better to just avoid symlinks altogether and accept the risk that formerly-symlinked schemas could get out of sync.

**Comment by jklukas** [comment]
We no longer are using symlinks.
