### ISSUE TITLE
update sync ping schema more :) `devices` array is now directly under `payload`

### ISSUE THREAD

**Issue by irrationalagent** [mozilla-services/mozilla-pipeline-schemas#473]
In the sync ping, [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1582263) moved the `devices` field (nullable array of structs/maps) to be directly under `payload` rather than nested within each member of the `syncs` array. we should update the pipeline schema to reflect this.

it will help with not having to write ugly queries [like this](https://sql.telemetry.mozilla.org/queries/67386/source)

**Comment by jklukas** [comment]
The new field should be deployed later today, so we'll be able to see pings with the top-level field correctly populated in a few days.
