### ISSUE TITLE
integrate-clean test failing on master

### ISSUE THREAD

**Issue by jklukas** [mozilla-services/mozilla-pipeline-schemas#493]
The current commit on master (https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/63dcb4285b73c0c625cbee46cf1fe506b7f4c5f6) is failing the `integrate-clean` CI test:

> RuntimeError: missing a data folder with submission date

It's unclear to me whether this is a problem with CI data or with the content of the schemas.

cc @acmiyaguchi

**Comment by acmiyaguchi** [comment]
The image will need to be bumped to v1.5.0 to start pulling in data from GCP. The repo will also need to be provisioned with a service account that has access to the `monitoring` dataset. Currently, this dataset is not available for use in CI. It will fail with the following message, as per https://github.com/mozilla-services/edge-validator/pull/45#issue-358816836

```
google.api_core.exceptions.Forbidden: 403 Access Denied: Table moz-fx-data-shared-prod:monitoring.document_sample_nonprod_v1: User does not have permission to query table moz-fx-data-shared-prod:monitoring.document_sample_nonprod_v1.
```

**Comment by jklukas** [comment]
Do you understand why the existing test started failing, though? Wasn't this previously working with the static data in S3?

**Comment by acmiyaguchi** [comment]
It looks like `integrate-clean` has been failing for a while now (likely starting when `telemetry-parquet` was deleted in S3), so this behavior isn't new.
