### ISSUE TITLE
Support YAML for writing schemas

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla-services/mozilla-pipeline-schemas#496]
[YAML](https://yaml.org/) is a human-friendly data serialization standard. It can be used to generate JSON in a straightforward way. This would make our schemas a bit more compact too. 

Here's a copy of a schema written in YAML, for reference:

https://github.com/mozilla-releng/buildhub2/blob/a240a7c4ed3ea2a5637f90537f40ff495ac58ce0/schema.yaml#L1-L129

**Comment by jklukas** [comment]
I believe Glean uses yaml for defining JSON schemas as well.

**Comment by acmiyaguchi** [comment]
Here's a glean schema -- one thing I notice is the use of comments:

https://github.com/mozilla/glean/blob/d3b222c891b447fa3a646cab9e5721411ea80ce1/glean-core/pings.yaml#L1-L73

**Comment by jklukas** [comment]
I'm concerned about increased cognitive burden if we have both json and yaml schema definitions sitting together in this repository. Even if all the schemas were defined in yaml, there's the cognitive burden of having to understand JSONSchema and then also having to understand how JSONSchema is represented as yaml. Currently, users can go reference arbitrary documentation about JSONSchema and the examples will be directly relevant to what they can write in this repository, even if manually writing the json is cumbersome.

It's worth thinking about and weighing the merits vs. the additional complexity.

**Comment by acmiyaguchi** [comment]
> I'm concerned about increased cognitive burden if we have both json and yaml schema definitions sitting together in this repository.

This is a fair point, YAML can get complicated especially with uses of anchors and aliases. If this were to be carried out, I imagine replacing all of the `templates` json files with a generated yaml equivalent, and ensuring the `schemas` json files are static. 

Some pros:
* Less brackets and vertical space during editing
* Ability to use [anchors and aliases](https://confluence.atlassian.com/bitbucket/yaml-anchors-960154027.html)
* Comments in schemas

Some cons:
* Documentation about JSON Schema is written in JSON, not YAML
* Rendered schemas are in JSON, which requires more effort to determine if changes are correct by hand
* Templates would need to be all or nothing, otherwise cmake includes would need to be written multiple times

**Comment by acmiyaguchi** [comment]
Given our existing template system utilizing a significant amount of JSON, this is not worth the effort.
