### ISSUE TITLE
Allow running tests on Debian/Ubuntu

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-services/mozilla-pipeline-schemas#66]
Currently, the `ctest -V -C hindsight` command fails due to the lua sandbox dependencies not being available on Debian/Ubuntu. Making testing work on such platforms (or Windows!), would make development much smoother.

**Comment by Dexterp37** [comment]
@trink is this something that can be easily solved by making the .deb files available for download somewhere?

**Comment by trink** [comment]
The integration tests use/test the installed production packages (including the schema package) just install the required packages before running the tests.  If you are running something other that these https://hsadmin.trink.com/packages/ you will have to build your own and then install..

**Comment by trink** [comment]
The other option is to run this on the already setup schema test box (test.trink.com)
