### ISSUE TITLE
Add `contentWin32kLockdownState` to the environment telemetry schema

### ISSUE THREAD

**Issue by marti4d** [mozilla-services/mozilla-pipeline-schemas#679]
[This commit](https://hg.mozilla.org/mozilla-central/rev/244764010fd8) to Mozilla Central added a new field, `contentWin32kLockdownState`, to the `environment` part of `telemetry.jsm`, next to the existing `effectiveContentProcessLevel`

When possible, please update the schema to reflect this so the Sandboxing team can monitor stats around the deployment of the Win32k Lockdown security feature.

The type of the new field is the same as the one above it (either an integer or `null`), and the description for it is in `environment.rst`, but for convenience it says "`The status of Win32k Lockdown for Content process`"

Thanks!

**Comment by marti4d** [comment]
PR #685

**Comment by fbertsch** [comment]
Fixed, thanks @marti4d!
