### ISSUE TITLE
CI `test` step currently failing on all PRs

### ISSUE THREAD

**Issue by jklukas** [mozilla-services/mozilla-pipeline-schemas#696]
Example failure: https://app.circleci.com/pipelines/github/mozilla-services/mozilla-pipeline-schemas/2547/workflows/d47fc074-80bc-4c9c-bb08-56e1a7fb6e79/jobs/5054

```
#!/bin/sh -eo pipefail
docker run mps

============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.0.2, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /app
plugins: forked-1.3.0, xdist-2.1.0
collecting ... 

Too long with no output (exceeded 10m0s): context deadline exceeded
```

This appears to be happening on all CI runs right now, which will prevent us confidently merging PRs.

**Comment by wlach** [comment]
Last successful run appears to be this one, on main: https://app.circleci.com/pipelines/github/mozilla-services/mozilla-pipeline-schemas/2538/workflows/5b7c935f-0170-4489-88c1-187e9eaf79aa

**Comment by wlach** [comment]
Seems to occur on new pull requests though, no matter what the docker version. I can reproduce it via ssh by running this:

`pytest tests/test_mps_bigquery.py`

Error log output:

https://gist.github.com/wlach/3f1e1d079937da3a30c5b48b5f979ac6

Other pytest invocations (e.g. `pytest tests/test_validation_python.py`) work fine.

The salient error seems to be `JVM exception occurred: com/mozilla/telemetry/ingestion/sink/config/SinkConfig has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 java.lang.UnsupportedClassVersionError`

**Comment by wlach** [comment]
Dollars to donuts the problem is this commit in gcp-ingestion: https://github.com/mozilla/gcp-ingestion/commit/cfc826cf657bfc78b15169de5a328705aeb82d64

Possible mitigations:

1. Upgrade java version used in this repo
2. Revert the above commit

**Comment by jklukas** [comment]
Thanks so much for tracking this down. This makes sense to me, that the CI here is running Java 8, but we're producing a Java 11 artifact from gcp-ingestion now.

> Upgrade java version used in this repo

If we can make that work, then we should move that direction. cc @relud

**Comment by wlach** [comment]
Currently investigating the upgrade approach in https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/698
