### ISSUE TITLE
Bug 1753742 - Update schema for DNSSEC interference study ping to include data for additional queries

### ISSUE THREAD

**Issue by ahounsel** [mozilla-services/mozilla-pipeline-schemas#718]
We would like to update the schema for the dnssec-study-v1 custom ping to support several new fields. These fields are implemented in `payload.dnsData` and `payload.dnsAttempts`. 

The new fields in `payload.dnsData` are described below:
- (udp/tcp) ACD: DNS response for a query for our A record with the CD=1 flag set over UDP and TCP.
- (udp/tcp) ADOCD: DNS response for a query for our A record with the DO=1 and CD=1 flags set over UDP and TCP.
- (udp/tcp) NEWTHREE: DNS response for a query for a custom RRTYPE we defined as NEWTHREE over UDP and TCP.
- (udp/tcp) NEWFOUR: DNS response for a query for a custom RRTYPE we defined as NEWFOUR over UDP and TCP.

The new fields in `payload.dnsAttempts` are described below:
- (udp/tcp) ACD: Number of queries attempted for our A record with the CD=1 flag set over UDP and TCP.
- (udp/tcp) ADOCD: Number of queries attempted for our A record with the DO=1 and CD=1 flags set over UDP and TCP.
- (udp/tcp) NEWTHREE: Number of queries attempted for a custom RRTYPE we definied as NEWTHREE over UDP and TCP.
- (udp/tcp) NEWFOUR: Number of queries attempted for a custom RRTYPE we defined as NEWFOUR over UDP and TCP.

The payload.dnsData object takes eight new fields:
```
            "udpACD": {
              "items": {
                "type": "integer"
              },
              "type": "array"
            },
            "udpADOCD": {
              "items": {
                "type": "integer"
              },
              "type": "array"
            },
            "udpNEWTHREE": {
              "items": {
                "type": "integer"
              },
              "type": "array"
            },
            "udpNEWFOUR": {
              "items": {
                "type": "integer"
              },
              "type": "array"
            }
            "tcpACD": {
              "items": {
                "type": "integer"
              },
              "type": "array"
            },
            "tcpADOCD": {
              "items": {
                "type": "integer"
              },
              "type": "array"
            },
            "tcpNEWTHREE": {
              "items": {
                "type": "integer"
              },
              "type": "array"
            },
            "tcpNEWFOUR": {
              "items": {
                "type": "integer"
              },
              "type": "array"
            }
```

The payload.dnsAttempts object also takes eight new fields:
```
            "udpACD": {
              "minimum": 0,
              "type": "number"
            },
            "udpADOCD": {
              "minimum": 0,
              "type": "number"
            },
            "udpNEWTHREE": {
              "minimum": 0,
              "type": "number"
            },
            "udpNEWFOUR": {
              "minimum": 0,
              "type": "number"
            },
            "tcpACD": {
              "minimum": 0,
              "type": "number"
            },
            "tcpADOCD": {
              "minimum": 0,
              "type": "number"
            },
            "tcpNEWTHREE": {
              "minimum": 0,
              "type": "number"
            },
            "tcpNEWFOUR": {
              "minimum": 0,
              "type": "number"
            }
```

You can find the commit that implements these fields [here](https://github.com/ahounsel/mozilla-pipeline-schemas/commit/21c097c0d0c877d354dab23194190e1620247bd4). I also updated the validation tests for the ping to include the new fields.

As an aside, is the schema automatically validated on the backend before it gets implemented? I've tested the schema on my own, but it would be nice to have some additional assurance :)

**Comment by jklukas** [comment]
Replaced by https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/719
