### ISSUE TITLE
Ensure that "shield-study" pings are being validated properly

### ISSUE THREAD

**Issue by mreid-moz** [mozilla-services/mozilla-pipeline-schemas#73]
The `shield-study` ping has two different `version` fields [here](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/schemas/telemetry/shield-study/shield-study.3.schema.json#L426) and [here](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/schemas/telemetry/shield-study/shield-study.3.schema.json#L453). We should test to make sure that the correct version is being used to identify the schema during ingestion.

**Comment by fbertsch** [comment]
@mreid-moz is this still needed?

**Comment by mreid-moz** [comment]
I believe it is still needed. Last time I checked, it didn't look like we were actually validating incoming shield pings against the schema at all.

**Comment by acmiyaguchi** [comment]
I've noticed that an that there was a non-zero error rate when was testing schema validation. If we bump the version number i.e. `shield-study.4.schema.json`, the error rate on the same sample will probably go to zero. Then, it should be safe to validating then if the starting error on the entire landfill is zero.

**Comment by jtg567** [comment]
fwiw I've never experienced issues with any of the derived shield datasets performing analyses

**Comment by acmiyaguchi** [comment]
@jtg567 This bug provides some more context about enabling validation. The worst case right now is a noisy datasets from experiments that are still running beyond their end date. I want to be sure before flipping the switch to avoid data loss.

[Bug 1392250 - Apply schema validation as expected for Shield Study pings](https://bugzilla.mozilla.org/show_bug.cgi?id=1392250)

**Comment by whd** [comment]
In terms of the output parquet schema, it appears the main issue we're seeing is that `payload.version` can be missing as a result of not applying these schemas.

**Comment by acmiyaguchi** [comment]
This is likely no longer relevant, closing this issue.
