### ISSUE TITLE
The CI build fails to pick up the latest RPMs

### ISSUE THREAD

**Issue by trink** [mozilla-services/mozilla-pipeline-schemas#95]
All CI jobs are failing

**Comment by Dexterp37** [comment]
Is [this](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/93/commits/3d5ba2c3c02422b9004a17be929819b6bf8d0420) the right fix?

**Comment by trink** [comment]
Until we go 1.0 ;) but yeah

**Comment by acmiyaguchi** [comment]
CI build seems to be working okay now.
